name: notification_overlay
description: A custom notification overlay for Android TV
version: 0.0.1
homepage: https://github.com/ghassenbenzahra123/custom-android-tv-notification

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.notification_overlay
        pluginClass: NotificationOverlayPlugin
  assets:
    - assets/mawaqitLogo.png